//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7769
        ///6798
        ///11685
        ///10826
        ///11807
        ///5786
        ///7932
        ///
        ///54883
        ///
        ///7069
        ///5792
        ///1519
        ///7380
        ///7034
        ///6203
        ///5706
        ///1850
        ///4933
        ///5562
        ///3826
        ///6661
        ///
        ///9150
        ///6417
        ///5057
        ///3568
        ///9352
        ///7134
        ///6040
        ///2451
        ///2295
        ///
        ///10996
        ///11802
        ///5525
        ///5705
        ///8266
        ///3742
        ///
        ///5140
        ///5527
        ///5686
        ///2488
        ///2518
        ///6260
        ///1692
        ///3149
        ///9109
        ///
        ///22590
        ///17677
        ///25444
        ///
        ///4146
        ///2282
        ///1957
        ///3673
        ///4830
        ///3220
        ///3823
        ///4619
        ///3222
        ///4076
        ///4594
        ///4550
        ///4806
        ///
        ///1426
        ///2726
        ///3566
        ///4089
        ///2195
        ///1512
        ///2547
        ///2284
        ///5687
        ///7429
        ///1043
        ///
        ///7877
        ///7446
        ///9753
        ///3184
        ///5417
        ///2306
        ///1680
        ///7121
        ///
        ///21326
        ///26045
        ///
        ///22638
        ///7066
        ///10062
        ///
        ///8585
        ///9072
        ///3466
        ///
        ///7022
        ///2085
        ///4942
        ///4034
        ///4285
        ///2498
        ///9268
        ///1444
        ///3302
        ///
        ///13269 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
    }
}
